import { signOut, useSession } from "next-auth/react"
import { api } from "~/utils/api"
import Head from "next/head"

const Home = () => {
    const createDonation = api.post.createDonation.useMutation()
    const { status } = useSession()

    if (status === "loading") {
        return <main>Loading...</main>
    }

    const handleCreateDonation = () => {
        createDonation.mutate(
            {
                donator_id: "cll2ku9se0002i3rsd4qom4tu",
                post_id: "c19cbad6-594b-4937-9d6a-90af36995b6b",
                reachedDate: new Date(),
            },
            {
                onSuccess: (donation) => {
                    console.log("---------------  Donations  ----------------")
                    console.log(donation)
                },
            }
        )
    }

    // const data = api.post.getAllPosts.useQuery()

    const handleFetchPosts = () => {
        // console.log("**************  Data  **************")
        // console.log(data.data)
    }

    return (
        <>
            <Head>
                <title>Waste-Aid</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="flex flex-col items-center justify-center gap-3 pt-5">
                    <button
                        className="btn-primary"
                        onClick={() => void signOut()}
                    >
                        SignOut
                    </button>
                    <button className="btn-primary">Update Post</button>
                    <button
                        className="btn-primary"
                        onClick={handleCreateDonation}
                    >
                        Create Donations
                    </button>
                    <button className="btn-primary" onClick={handleFetchPosts}>
                        Fetch Posts
                    </button>
                </div>
            </main>
        </>
    )
}

export default Home
