import { signOut, useSession } from "next-auth/react"
import Head from "next/head"

const Home = () => {
    const { status } = useSession()

    if (status === "loading") {
        return <main>Loading...</main>
    }

    // const data = api.post.getAllPosts.useQuery()

    const handleFetchPosts = () => {
        // console.log("**************  Data  **************")
        // console.log(data.data)
    }

    return (
        <>
            <Head>
                <title>Waste-Aid</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="flex flex-col items-center justify-center gap-3 pt-5">
                    <button
                        className="btn-primary"
                        onClick={() => void signOut()}
                    >
                        SignOut
                    </button>
                    <button className="btn-primary">Update Post</button>
                    <button className="btn-primary">Create Donations</button>
                    <button className="btn-primary" onClick={handleFetchPosts}>
                        Fetch Posts
                    </button>
                </div>
            </main>
        </>
    )
}

export default Home
